#!/bin/bash
set -euv

git clone --depth 1 --branch dev git://code.qt.io/qt/qtbase.git /geordi/src/qtbase
cd /geordi/src/qtbase
echo "QMAKE_CXXFLAGS += -Wno-class-memaccess" >> mkspecs/linux-g++/qmake.conf
export CXX=/usr/local/bin/g++
export LD_LIBRARY_PATH=/usr/local/lib64
g++ --version
./configure -prefix /usr/local/qt5 -opensource -confirm-license -no-dbus -no-widgets -no-feature-sql -no-feature-testlib -nomake tests -nomake examples -nomake tools
make -j2
make install
